spring:
  application:
    name: course-management-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/course-management-service}
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: course-management-service
      auto-offset-reset: earliest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
server:
  port: 8081